# Generated by Django 4.2.2 on 2023-06-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_category_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("current_bid", models.IntegerField()),
                ("creation_date", models.DateTimeField()),
                ("available", models.BooleanField()),
                ("description", models.CharField(max_length=128)),
            ],
        ),
    ]
