# Generated by Django 4.2.2 on 2023-06-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_auction_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="photos",
            field=models.ManyToManyField(
                blank=True, related_name="photos", to="auctions.photo"
            ),
        ),
    ]
